---
title: "Artificial Intelligence Research Protocol Template for EC Submission"
subtitle: "Subtitle"
format:
  docx:
    reference-doc: "ref/th-sarabun-new-ref-ethic-proprosal.docx"
bibliography: "ref/references.bib"
link-citations: true
---

(All information can be written in Thai or English. Descriptions in red must be deleted before submission)

+:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Study Title (English):**                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Study Title (Thai):**                                                                                                                                                                                                                                                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Principal investigator:**                                                                                                                                                                                                                                                                                  |
|                                                                                                                                                                                                                                                                                                              |
| \<please include name, affiliation and contact data, signed and dated CV is required in separate documents\>                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Co-investigator(s):**                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                              |
| *\<please include name, affiliation and contact data, signed and dated CVs of all co-investigators are required in separate documents\>*                                                                                                                                                                     |
|                                                                                                                                                                                                                                                                                                              |
| *\<Please remark who is the advisor for student/resident research project\>*                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Sponsor or planned sponsor, grant, scholarship \<if applicable\>:**                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                              |
| \<please note that Mahidol University do not allow using of healthcare insurance or beneficiary for research purpose. If the investigator believe that all study procedures in the study are within reimbursable standard of care, please enclose letter of confirmation from the head of the department. \> |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Conflict of Interest:**                                                                                                                                                                                                                                                                                    |
|                                                                                                                                                                                                                                                                                                              |
| **\<** describe any potential issue that the outcome of the research may lead to a investigators’ personal advantage, and that might compromise the integrity of the research.                                                                                                                               |
|                                                                                                                                                                                                                                                                                                              |
| -   Do investigator or their immediate family or someone with whom they are in a close personal relationship is working for pharmaceutical company that sponsor the clinical trial?                                                                                                                          |
|                                                                                                                                                                                                                                                                                                              |
| -   Do investigators receive honorarium from pharmaceutical company that sponsor this clinical trial and how much?                                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                                              |
| -   In case of receiving educational non-restrictive grant, letter of intent from sponsor is needed.\>                                                                                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Study sites (list all as planned):**                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                              |
| **\<** *This section is based on your research question. How would you answer the questions and give explanations to your answer? What are the assumptions and relationships?\                                                                                                                               |
| Justification of your conducting this study based on existing knowledge and your research question.*                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                              |
| *- Describe the disease including incidence*                                                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                              |
| *- Provide summary of previous relevant studies. Details should be enough to show that thorough literature reviews have been done and investigator has adequate expertise in that research question.\                                                                                                        |
| - Each reference from the literature should be cited in the text using superscript or blanket/parentheses arabic numerals. List of references should be put at the end of protocol.\                                                                                                                         |
| - In the last paragraph, please state the main purpose/rational of the study summarizing all the information provided in your background section.*                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                                              |
| *You need to clearly answer the question, ‘What we will know as a result of this study that we do not know before?’\>*                                                                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Objectives:**                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                                              |
| **Primary Objective:**                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                              |
| **\<** *The primary objective is the main question to be answered by the results of the study, which determines study design and sample size. **\>***                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                              |
| *\< use action verb and specify population, intervention, control and outcome\>*                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                              |
| **Secondary Objectives:**                                                                                                                                                                                                                                                                                    |
|                                                                                                                                                                                                                                                                                                              |
| \< *Secondary objectives are additional questions to be addressed, if possible, which can be two or three can be dependent or independent of the primary objective.\>*                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Study design/methodology:**                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                              |
| *Explains the procedures that will be used to achieve the objectives. In this section, details of the variables (input and outcome features) and the ways to measure them should be included.\                                                                                                               |
| How are you planning to do this study? Details of the methods and procedures should be included.*                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                              |
| *Detail the process of data extraction/collection including training of extraction/collection personnel, extraction/case record forms to be used, and the data flow.*                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                              |
| ***Including of study flow diagram or clinical trial flow (CONSORT) is required!!!! \>***                                                                                                                                                                                                                    |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Study Population:**                                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                              |
| **State the selection of study subjects including controls, giving the inclusion and exclusion criteria and period / place of recruitment.**                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                              |
| **Data sources and period of study.**                                                                                                                                                                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Statistical Analysis Plan:**                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                              |
| Give the procedure for data analysis, including data retrieval, data management, statistical analysis to be carried out, data mining techniques, software to be used, data storage and security.                                                                                                             |
|                                                                                                                                                                                                                                                                                                              |
| Which algorithm will be applied and how to perform the performance.                                                                                                                                                                                                                                          |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Sample size determination:**                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                              |
| *Indicate how the sample size has been determined with equation, and allowance for loss to follow up.*                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                              |
| How to split data (train/test), data imputation, data augmentation (if needed).                                                                                                                                                                                                                              |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ***Privacy and confidentiality (Data Management Plan):***                                                                                                                                                                                                                                                    |
|                                                                                                                                                                                                                                                                                                              |
| *\<Accroding to Thai Personal Data Protection Act 2019, this section is mandatory.*                                                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                                                                              |
| -   Who will be responsible for data management?                                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                              |
| -   How will new data be collected or produced?                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                                              |
| -   What data (for example the kind, formats), will be collected or produced?                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                              |
| -   How will the data be organized and recorded to ensure for both quality control and reproducibility?                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                              |
| -   How will data be stored and backed up during the research?                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                              |
| -   How will data security and protection of sensitive data be taken care of during the research?                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                              |
| -   How will compliance with legislation on personal data and on security be ensured If personal data are collected, stored, or processed?                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                              |
| -   Who, which investigators and research staff, will have access to biospecimens and data?                                                                                                                                                                                                                  |
|                                                                                                                                                                                                                                                                                                              |
| -   How will access be controlled?                                                                                                                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                                              |
| -   Any plans for sharing or providing access of the data.                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                              |
| Outline the plan for data preservation and give information on how long the data will be retained                                                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Ethical consideration:**                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                              |
| -   **Risks to participants and how to minimize the risks:**                                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                              |
| *\<Identify any risks and burdens involved while conducting the study and procedure to minimize such risk/burden\>*                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                                                                              |
| -   **Direct Benefits to Participants**                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                              |
| *\<Include potential benefit to health and wellbeing of participants. Please do not overclaim.\>*                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                              |
| -   **Scientific or social value**                                                                                                                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                                              |
| *\<Include potential knowledge advancement or application to the society.\>*                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                              |
| *Sample text: This study does not present the prospect of direct benefit to the participants. However, the study does provide an opportunity to gain a better understanding of…*                                                                                                                             |
|                                                                                                                                                                                                                                                                                                              |
| -   ***Justification if enrolling potentially vulnerable subjects.***                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                              |
| *\<Please specify the justification for enrolment of children and/or incapacitated adults participating in research especially non-therapeutic clinical trial. This should also be specified in the informed consent.*\>                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Study Timeline:**                                                                                                                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                                                                              |
| \<Provide timetable of the study                                                                                                                                                                                                                                                                             |
|                                                                                                                                                                                                                                                                                                              |
| *Sample language:*                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                                              |
| *screening, enrollment, ----6 months from January 20xx to June 20xx*                                                                                                                                                                                                                                         |
|                                                                                                                                                                                                                                                                                                              |
| *treatment phase -----6 months from …*                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                              |
| *data collection and data analysis -----2 months from ….\>*                                                                                                                                                                                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+